"""Crypto cross-backend compatibility tests.

The AES-256-GCM payload format MUST be byte-compatible with the Node backend
(apps/flow-backend/src/lib/crypto.ts). These tests pin that contract:

  1. A payload encrypted by Node decrypts correctly here.
  2. A payload encrypted here decrypts correctly in Node (verified via the
     roundtrip: Python-encrypt → Python-decrypt yields original).
  3. Format invariants: prefix, base64 length structure, IV/tag slicing.

The Node-generated test vector below was produced by apps/flow-backend's
crypto.ts with a fixed 32-byte key. If the Python crypto layer is correct,
decrypt(vector) must return the original plaintext.
"""

from __future__ import annotations

import base64
import os
from unittest.mock import patch

import pytest

from app.utils import crypto
from app.utils.crypto import PREFIX, decrypt, encrypt, is_encrypted

# Generated by Node's lib/crypto.ts with a fixed key + IV.
# plaintext = "super-secret-api-key"
NODE_TEST_KEY_B64 = "1dF+rAam05a3N903U6U8l1JXgM7YQS7AsL237sZRZdg="
NODE_TEST_PAYLOAD = "enc::MDEyMzQ1Njc4OTAxLKBv9bt85R9oaie26TT+3ielyQ36uTbWMvZNRXUau3UKlX12"
NODE_TEST_PLAINTEXT = "super-secret-api-key"


@pytest.fixture(autouse=True)
def _fixed_key(monkeypatch: pytest.MonkeyPatch) -> None:
    """Force the crypto layer to use the test key for all tests in this module."""
    monkeypatch.setenv("FLOWGRAM_ENCRYPTION_KEY", NODE_TEST_KEY_B64)
    # get_settings is lru_cached; clear it so the new env var takes effect.
    from app.core import config

    config.get_settings.cache_clear()


class TestNodeInterop:
    """Python decrypts what Node encrypted — the core cross-backend invariant."""

    def test_decrypts_node_payload(self) -> None:
        assert decrypt(NODE_TEST_PAYLOAD) == NODE_TEST_PLAINTEXT

    def test_node_payload_has_correct_structure(self) -> None:
        """Verify the Node payload's byte layout matches our assumed slicing."""
        raw = base64.b64decode(NODE_TEST_PAYLOAD[len(PREFIX):])
        assert len(raw) >= 12 + 16  # iv + tag minimum
        iv = raw[:12]
        tag = raw[12:28]
        ciphertext = raw[28:]
        assert len(iv) == 12
        assert len(tag) == 16
        assert len(ciphertext) > 0  # non-empty plaintext


class TestRoundtrip:
    """Python encrypt → Python decrypt yields the original."""

    @pytest.mark.parametrize(
        "plaintext",
        [
            "hello world",
            "sk-xxxxxxxxxxxxxxxxxxxxxxxx",
            "_unicode_emoji_🚀_测试",
            '{"json":"value","num":123}',
            "a",  # single char
        ],
    )
    def test_roundtrip(self, plaintext: str) -> None:
        encrypted = encrypt(plaintext)
        assert encrypted != plaintext
        assert encrypted.startswith(PREFIX)
        assert decrypt(encrypted) == plaintext

    def test_encrypt_uses_random_iv(self) -> None:
        """Same plaintext encrypts to different ciphertext (random IV)."""
        a = encrypt("same")
        b = encrypt("same")
        assert a != b
        assert decrypt(a) == decrypt(b) == "same"


class TestPassthrough:
    """Empty/non-payload values pass through unchanged (matches Node)."""

    def test_encrypt_empty_returns_empty(self) -> None:
        assert encrypt("") == ""

    def test_decrypt_empty_returns_empty(self) -> None:
        assert decrypt("") == ""

    def test_decrypt_non_payload_returns_input(self) -> None:
        assert decrypt("not-encrypted") == "not-encrypted"
        assert decrypt("plain text") == "plain text"

    def test_is_encrypted(self) -> None:
        assert is_encrypted("enc::xxx") is True
        assert is_encrypted("plain") is False
        assert is_encrypted(None) is False  # type: ignore[arg-type]
        assert is_encrypted(123) is False  # type: ignore[arg-type]


class TestErrorHandling:
    def test_missing_key_raises(self, monkeypatch: pytest.MonkeyPatch) -> None:
        # Force the crypto layer to see an empty key. We patch the loader so the
        # .env file (present when running the live server) doesn't resupply it.
        monkeypatch.setattr(
            "app.utils.crypto._load_key",
            lambda: (_ for _ in ()).throw(crypto.CryptoConfigError("FLOWGRAM_ENCRYPTION_KEY is not set")),
        )
        with pytest.raises(crypto.CryptoConfigError, match="not set"):
            encrypt("x")

    def test_wrong_key_raises_invalid_tag(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """Decryption with a different key fails (auth tag mismatch)."""
        # Encrypt with the test key, then swap to a different key.
        encrypted = encrypt("secret")
        wrong_key = base64.b64encode(b"B" * 32).decode()
        monkeypatch.setenv("FLOWGRAM_ENCRYPTION_KEY", wrong_key)
        from app.core import config

        config.get_settings.cache_clear()
        from cryptography.exceptions import InvalidTag

        with pytest.raises(InvalidTag):
            decrypt(encrypted)
